### PR TITLE
fix: PyGithub 1.58+ support

### PR DESCRIPTION
**Pull request by BoboTiG**
Hello,

Here is a patch to support PyGithub 1.58+, fix mypy issues, and also improve packaging checks by adding classifiers.

I also fixed `slap run fmt`, and actually run the command. It explains the number of changes. I did it in a separate commit to ease the review.

### CODE REVIEW

**Comment by BoboTiG** [comment]
(Tests failures are not related to those changes, they failed even before.)

**Comment by NiklasRosenstein** [comment]
Thanks @BoboTiG 🙌

**Comment by NiklasRosenstein** [comment]
Actually I got one small follow up question: Did anything **prevent** you from using the current version of python-github-bot-api with PyGithub 1.58+?

**Comment by NiklasRosenstein** [comment]
Released in 0.5.2

**Comment by BoboTiG** [comment]
> Actually I got one small follow up question: Did anything prevent you from using the current version of python-github-bot-api with PyGithub 1.58+?

Yes, it wasn't possible at all given the `AttributeError`. See the information in the test.

**Comment by NiklasRosenstein** [comment]
Ah yes of course, you did mention that in the test. Thanks!

**Pull request merged**
