### PR TITLE
Don't decode already decoded object

### LINKED ISSUE #7: The upgrade to PyJWT > 2.0 has resulted in an exception when attempting to decode a string
The following issue was caused by https://github.com/NiklasRosenstein/python-github-bot-api/commit/c8eac8cf52ee3055c7c076abb05ba2e0ec55d00e

PyJWT returns an already-decoded string now instead of bytes:
https://github.com/jpadilla/pyjwt/pull/513

```
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\githubrepokeeper\__main__.py", line 115, in <module>
    github_api = github_app.installation_client(
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\github_bot_api\app.py", line 211, in installation_client
    token = self.installation_token(installation_id).value
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\github_bot_api\app.py", line 189, in installation_token
    return self.get_installation_token_supplier(installation_id)()
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\github_bot_api\token.py", line 86, in __call__
    self._cached_token = self._new_token()
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\github_bot_api\token.py", line 145, in _new_token
    data = self.requestor(self.app_jwt().auth_header, self.installation_id)
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\github_bot_api\token.py", line 86, in __call__
    self._cached_token = self._new_token()
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\github_bot_api\token.py", line 116, in _new_token
    return create_jwt(self.app_id, self.expires_in, self.private_key)
  File "C:\devel\venvs\gh-repo-keeper\lib\site-packages\github_bot_api\token.py", line 61, in create_jwt
    token = jwt.encode(payload, private_key, algorithm='RS256').decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
```

### PR DESCRIPTION
**Pull request by testworksau**
Fixes https://github.com/NiklasRosenstein/python-github-bot-api/issues/7

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Hey @testworksau , it seems PyJWT 2 ships with its own typing information, so we need to remove types-PyJWT from the dependencies.

**Comment by testworksau** [comment]
Thanks @NiklasRosenstein, hopefully that fixes the tests 🤞🏼

**Comment by NiklasRosenstein** [comment]
Thanks! :)

**Comment by NiklasRosenstein** [comment]
Published as 0.5.1 !

**Comment by testworksau** [comment]
It works! Thanks @NiklasRosenstein 🎉

**Pull request merged**
