### PR TITLE
Introduce GithubClientSettings

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
Addresses #4 and #3

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Hey @testworksau 👋 Could I ask you to give this branch a try and see if it fits your needs?

**Comment by testworksau** [comment]
Sure thing, I will give it a whirl on Monday and let you know - thanks!!!

**Review by testworksau — APPROVED** [review]
Sorry for being a day late @NiklasRosenstein - I've updated my code to pass in the settings dict and all looks good 🎉 

```
github_settings = dict(
    per_page=100,
    retry=retry
)
github_api = github_app.installation_client(
    installation_id=get_installation_id_for_org(org_slug),
    settings=github_settings
)
```

Just one thing to mention though - on L56 in `make_client` did you mean to use the raw `self.user_agent`? 

Just asking as the user agent used to be generated by `get_user_agent()` and the code still says it will be respected in the same method, which is now (internally) unused.

**Comment by testworksau** [comment]
@NiklasRosenstein any thoughts on the above?

**Comment by NiklasRosenstein** [comment]
Hey @testworksau, thanks for the follow up! I updated it to pass the result of `GithubApp.get_user_agent()` to the `GithubClientSettings`!

**Comment by NiklasRosenstein** [comment]
Published as 0.4.0 !

**Pull request merged**
